export const data = [
  {
    id: 0,
    name: "ალექსადრიტის ლაზერი",
    image1: "./images/Productsimages/alexandrit2.jpg",
    image2: "./images/Productsimages/alexandrit3.png",
    image3: "./images/Productsimages/alexsadrit.jpg",
  },
  {
    id: 1,
    name: "ლაზერული ეპილაციის აპარატი - Soprano Ice Platinum ანალოგი",
    image1: "./images/Productsimages/epilacia3.jpg",
    image2: "./images/Productsimages/epilacia.1.jpg",
    image3: "./images/Productsimages/epilacia.2.jpg",
  },
  {
    id: 2,
    name: "მრავალფუნქციური სახის ღრმა წმენდის აპარატი",
    image1: "./images/Productsimages/face_cleaner.jpg",
    image2: "./images/Productsimages/face_cleaner1.jpg",
    image3: "./images/Productsimages/face_cleaner2.jpg",
  },
  {
    id: 3,
    name: "კავიტაციის აპარატი",
    image1: "./images/Productsimages/kavi.jpg",
    image2: "./images/Productsimages/kavi1.jpg",
    image3: "./images/Productsimages/kavi2.jpg",
  },
  {
    id: 4,
    name: "პრემიუმ ხარისხის კრიოლიპოლიზის აპარატი",
    image1: "./images/Productsimages/krio.jpg",
    image2: "./images/Productsimages/krio1.jpg",
    image3: "./images/Productsimages/krio2.jpg",
  },
  {
    id: 5,
    name: "კრიოლიპოლიზის აპარატი",
    image1: "./images/Productsimages/kriopoliz.jpg",
    image2: "./images/Productsimages/kriopoliz1.jpg",
    image3: "./images/Productsimages/kriopoliz2.jpg",
  },
  {
    id: 6,
    name: "დიოდური ლაზერის ეპილაციის აპარატი",
    image1: "./images/Productsimages/laser_blue.jpg",
    image2: "./images/Productsimages/laser_blue1.jpg",
    image3: "./images/Productsimages/laser_blue2.jpg",
  },
  {
    id: 7,
    name: "პრემიუმ კლასის დიოდური ლაზერის ეპილაციის აპარატი",
    image1: "./images/Productsimages/laser.jpg",
    image2: "./images/Productsimages/laser2.jpg",
    image3: "./images/Productsimages/laser3.jpg",
  },
  {
    id: 8,
    name: "3D შილაკის აპარატი",
    image1: "./images/Productsimages/shilak1.jpg",
    image2: "./images/Productsimages/shilak2.jpg",
    image3: "./images/Productsimages/shilak3.jpg",
  },
  {
    id: 9,
    name: "SonneX ფირმის სოლარიუმი",
    image1: "./images/Productsimages/solarium.jpg",
    image2: "./images/Productsimages/solarium1.jpg",
    image3: "./images/Productsimages/solarium2.jpg",
  },
  {
    id: 10,
    name: "MISMON -ფირმის პორტატული ლაზერის აპარატი",
    image1: "./images/Productsimages/wportat_laser.jpg",
    image2: "./images/Productsimages/wportat_laser2.jpg",
    image3: "./images/Productsimages/wportat_laser3.png",
  },
  {
    id: 11,
    name: "ვაკუუმ თერაპიის აპარატი",
    image1: "./images/Productsimages/vakuum.jpg",
    image2: "./images/Productsimages/vakuum1.jpg",
    image3: "./images/Productsimages/vakuum2.jpg",
  },
  {
    id: 12,
    name: "პორტატული ლაზერის აპარატი",
    image1: "./images/Productsimages/zportatuli_1.jpg",
    image2: "./images/Productsimages/zportatuli_2.jpg",
    image3: "./images/Productsimages/zportatuli.jpg",
  },
];
